--drop all
DROP TABLE Invoices CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Fee CASCADE CONSTRAINTS;
DROP TABLE Movie CASCADE CONSTRAINTS;
DROP TABLE Sale CASCADE CONSTRAINTS;
DROP TABLE Item CASCADE CONSTRAINTS;
DROP TABLE Award CASCADE CONSTRAINTS;
DROP TABLE Purchase_Order CASCADE CONSTRAINTS;
DROP TABLE Catalog CASCADE CONSTRAINTS;
DROP TABLE Distributor CASCADE CONSTRAINTS;
